apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
    - name: centos7
      image: centos:7
      volumeMounts:
        - name: volume1
          mountPath: /data
  volumes:
    name: volume1
    emptyDir: {}
