apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-sc1
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: "/data"
          name: claim1
  volumes:
    - name: claim1
      persistentVolumeClaim:
        claimName: claim1